export * from './globals';
export { applyContext } from './applyContext';
export { cleanProps } from './cleanProps';
export { compressEntity } from './compressEntity';
export { compactJsonObject } from './compactJsonObject';
export { convertJsonToEntity } from './convertJsonToEntity';
export { convertEntityToJson } from './convertEntityToJson';
export { getCollectionNameByUrl } from './getCollectionNameByUrl';
export { getId } from './getId';
export { getEntity } from './getEntity';
export { isLocal } from './isLocal';
