export declare const PORT: number;
export declare const LOCAL_HOSTNAME: string;
export declare const PROTOCOL: string;
export declare const DB_NAME: string;
export declare const LOCAL_DOMAIN: string;
export declare const CONTEXT = "@context";
export declare const ACTIVITYSTREAMS_CONTEXT = "https://www.w3.org/ns/activitystreams#";
export declare const W3ID_SECURITY_CONTEXT = "https://w3id.org/security/v1";
export declare const RELATIONSHIP_CONTEXT = "http://purl.org/vocab/relationship/";
export declare const CHANGESET_CONTEXT = "http://purl.org/vocab/changeset/schema#";
export declare const PUBLIC_ACTOR: string;
export declare const LINKED_DATA_CONTENT_TYPE = "application/ld+json";
export declare const SERVER_ACTOR_USERNAME = "bot";
export declare const SERVER_ACTOR_ID: string;
export declare const SHARED_INBOX_ID: string;
export declare const ACCEPT_HEADER = "Accept";
export declare const CONTENT_TYPE_HEADER = "Content-Type";
export declare const ACTIVITYSTREAMS_CONTENT_TYPE_WITH_PROFILE: string;
export declare const ACTIVITYSTREAMS_CONTENT_TYPE = "application/activity+json";
export declare const JSON_CONTENT_TYPE = "application/json";
export declare const HTML_CONTENT_TYPE = "text/html";
export declare const USERNAME_REGEXP: RegExp;
export declare const RESERVED_USERNAMES: string[];
